### PR TITLE
Reworked hyperparameter optimization and added some other changes.

### PR DESCRIPTION
**Pull request by eugenioLR**
## Hyperparameters

Hyperparameters must now be defined as follows:
```
{
    'model': <Name>,
    <hyperparam_name>:
        Choose one of:
        - {"type": "real", "min": <number>, "max": <number>},
        - {"type": "integer", "min": <number>, "max": <number>},
        - {"type": "categorical", "values": [<number or string>]}
}
```

This way grid search can be done automatically given a model (given that it has a definition). 

There is a new file (hyperparam_info.json) that holds the definitions of most of the available models and a new method (add_known_model_def) that allows the user to add custom definitions of hyperparameters.

There is still the option to define an hyperparameter grid for each model if you don't want to rely on this new generation of hyperparameters.

## Hyperparam. optimization pipeline
The hyperparameter optimization pipeline now includes a step where only the best parameters are found without fitting the actual model, this implies an increase in running time since more training steps must be done, however, this gives the user the option of just obtaining a good set of parameters for a set of models without having to go through the entire pipeline.

The optimization of hyperparameters is now also optional, you can simply train all the models with their default hyperparameters in case the user wants to perform a quick test with each model.

## Metrics
There is a new module (metric_alias.py) that defines shorthand names for sklearn metrics which can be used in the code instead of their original (and often ugly) name.  

## Logging
To display messages to the user we are going to use logging, which gives a lot of flexibility in terms of filtering messages by importance and redirecting important information to files. The logger is set to the level INFO, but it can be easily changed.

### CODE REVIEW

**Comment by vgarciasc** [comment]
Looks great! I like most of the changes, I think they move the project towards easeness-of-use and flexibility, which are its two essential characteristics. Some points:

1. Previously, the project supported hyperparameter searching, but the user had to provide the hyperparameter search space (which was the third tuple element in the `models` object). In this new version, the user can do hyperparameter search *without* providing any hyperparameters, because some models already have a default hyperparameter search space (defined in `hyperparam_info.json`). If the model is not included in the JSON file, then the user *must* provide a hyperparameter search space if they want to run hyperparameter search; otherwise, an exception is thrown. Is this understanding correct?

2. Previously, the hyperparameter tuning happened model-by-model (`tune_model` returned `clf.best_estimator`), while in the new code it is done simultaneously for all models (`tune_models` redefines `self.models`). However, this means that we are changing the model definitions for all future fits, which I think is unexpected behavior. For example:      
  
  ```python  
  data = load_iris()
  X, y = data.data, data.target
  
  hh = HundredHammersClassifier()
  df_results_1 = hh.evaluate(X, y, optim_hyper=False)
  df_results_2 = hh.evaluate(X, y, optim_hyper=True)
  df_results_3 = hh.evaluate(X, y, optim_hyper=False)
  print(df_results_1)
  print(df_results_2)
  print(df_results_3)
  ```   
  
  If you run this code, you will see that `df_results_3` is equal to `df_results_2`, instead of being equal to `df_results_1` (which would be the most natural equivalence, since both lack hyperparameter optimization). In this case it is perhaps OK for this behavior to happen, but notice that X and y could have changed between 2 and 3, which would mean that the results in 3 would use not default parameters (as requested by the user), but parameters optimized for a different dataset.

3. How do you see people using `add_known_model_def`? It's not clear to me how it compares to passing the `models` parameter to `HundredHammersBase`, for example. Are these equivalent ways of achieving the same goal? (Adding new models to the model list).

4. Previously, we used the `verbose` flag in `HundredHammersBase` to determine if progress should be printed. Now we are using the `logging` library, but it is not integrated with the `verbose` flag (which is still there, but now obsolete). Is this correct? If it is, I would suggest simply removing the `verbose` flag and offering another way for the user to configure logging.

**Comment by eugenioLR** [comment]
Let's go point by point:

1. Yeah, that's pretty much it, but the lack of hyperparameter definitions just skips their optimization without raising an exception. The user also has the option of adding a new hyperparameter definition with the ```add_known_model_def``` function if their model is not already defined in the ```known_hyperparams``` variable, i'll leave the explanation for point 3.

2. As you pointed out, this is unexpected behaviour, the original models shouldn't be modified directly. The only issue then is that the function to train the models would only return a Dataframe with the summary of the execution, and the models would have to be retrained. This might be the intended use of the library, but it could be a bit wasteful in terms or computing time.

3. The main purpose of this function is to add a definition to the list of registered models, expanding the amount of models for which the grid search can be done automatically. This, in essence, adds a new model to the ```known_hyperparams``` data structure, which holds the contents of the ```hyperparam_info.json``` file.

   This is different from directly defining the hyperparameter search space in the input of the ```HundredHammers``` class since it directly specifies the values that should be checked, instead of defining the type and bounds of each 
parameter.

   Notice that there is an schema object (```hyperparam_def_schema```) that defines the structure of each of the definitions of the models, this is the same schema that each model definition follows in the .json file.
The reason there is a step that raises an exception is because the ```add_known_model_def``` function verifies that the definition of hyperparameters passed as an input follows the schema.
Perhaps a couple of example scripts would be helpful not only for us, but the users of the library.

    For the use of the hyperparameter search space vs. the model definitions, it's a bit of a tradeoff, if you define the hyperparameters of a model, you can adjust the number of grid points (the parameter ```n_grid_points``` in the ```evaluate``` method) with an already existing instance of ```HundredHammer```. If you want more flexibility defining the parameters you want to search, you can pass directly the search space.

    I think they are both complementary, the model definitions serve as a quick and "easy" way of doing grid search, passing directly the parameters you want is a bit more costly, but gives more control to the user.
This is without even considering that, since we have the definitions of the hyperparameters of each model, we are not forced to use Grid search, we could use any optimization techinque we want (given that it fits to this type of problem), this could include something simple like Random search or Binary search, or something more sophisticated like Evolutionary algorithms.

5. You are right, i forgot to remove the verbose flag, it is not used anymore. For the configuration of the logger, since it uses an already existing logging library, users can configure it directly by calling methods on the defined logger object (```hh_logger```). 
This might need to be documented somewhere to refer users to the documentation of the logging library. 

Thank you very much for the review.

**Comment by eugenioLR** [comment]
I made a commit solving most of the issues and solving a couple of bugs.

Check the changes and tell me what you think.

**Comment by vgarciasc** [comment]
Thank you for the detailed comments. All issues I pointed out appear to be fixed, and it is clear to me now the usefulness of `add_known_model_def` over passing `models` as a parameter. Accepting this.

**Pull request merged**
